# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatrFleet < Formula
  desc "A beautiful terminal dashboard for your fleet of AI coding agents"
  homepage "https://github.com/edbror/watr-fleet"
  version "0.10.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.0/watr-fleet_0.10.0_darwin_amd64.tar.gz"
      sha256 "79fab4f106a4c9260646a6a211c4f013814598b3dd3686ec287d6d4f7d9a81ed"

      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.0/watr-fleet_0.10.0_darwin_arm64.tar.gz"
      sha256 "a24d33b334e59aa90d308b6f1ab702f62c264440f87b20b80841e437ef4b09aa"

      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.0/watr-fleet_0.10.0_linux_amd64.tar.gz"
      sha256 "ff5109b5f6a589f64d6f017c4c1e2345b8b00b4caf2b8c327bc631cde39d3eed"
      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.0/watr-fleet_0.10.0_linux_arm64.tar.gz"
      sha256 "78367ee2e7ce6b0da97b15cf3bf42f6bc149cbeed4f27405e59a65b1524561d9"
      define_method(:install) do
        bin.install "fleet"
      end
    end
  end
end
