# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatrFleet < Formula
  desc "A beautiful terminal dashboard for your fleet of AI coding agents"
  homepage "https://github.com/edbror/watr-fleet"
  version "0.10.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.1/watr-fleet_0.10.1_darwin_amd64.tar.gz"
      sha256 "58d8c8072258a78e302bf46f960facf075dc0dc89e5f0301397582a4fd0a3536"

      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.1/watr-fleet_0.10.1_darwin_arm64.tar.gz"
      sha256 "685e207c909982088f33b4f01e4ae2093a8dd09e0f4f0335ed0e83c68e4ece21"

      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.1/watr-fleet_0.10.1_linux_amd64.tar.gz"
      sha256 "873968a125bd2a49e73c1f78c2aacca5816eaadc819f9fb39d07d34dbe5aee58"
      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edbror/watr-fleet/releases/download/v0.10.1/watr-fleet_0.10.1_linux_arm64.tar.gz"
      sha256 "3df8819f5dbb23637c09b2e1864a9425e029114382a09bfce6e1135b4e0f9f33"
      define_method(:install) do
        bin.install "fleet"
      end
    end
  end
end
